config/routes.rb
Rails.application.routes.draw do
  resources :members
  resources :teams do
    member do
      post :add_members
      post 'remove_member/:member_id', to: 'teams#remove_member', as: :remove_member
    end
  end

  resources :projects do
    member do
      post :add_members
      post 'remove_member/:member_id', to: 'projects#remove_member', as: :remove_member
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
  validates_presence_of :first_name, :last_name
  has_many :team_members
  has_many :teams, through: :team_members

  has_many :project_members
  has_many :projects, through: :project_members
  validates :teams, length: { minimum: 1 }
  accepts_nested_attributes_for :teams, reject_if: ->(attributes){ attributes['id'].blank? }
  accepts_nested_attributes_for :projects, reject_if: ->(attributes){ attributes['id'].blank? }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_members
  has_many :members, through: :project_members
  validates_presence_of :name
end

app/models/project_member.rb
class ProjectMember < ApplicationRecord
  belongs_to :project
  belongs_to :member
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_members
  has_many :members, through: :team_members
  validates_presence_of :name
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  belongs_to :team
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to member_url(@member), notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :city, :state, :country, team_ids: [], project_ids: [])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy add_members remove_member ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_members
    new_members = Member.find(params[:member_ids].map(&:presence).compact)

    new_members.each do |member|
      @project.project_members.create_or_find_by(member_id: member.id)
    end

    redirect_to project_url(@project), notice: "Team was successfully updated."
  end

  def remove_member
    @project_member = @project.project_members.find_by_member_id(params[:member_id])
    @project_member.destroy
    redirect_to project_url(@project), notice: "Team member was successfully removed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy add_members remove_member ]

  # GET /teams or /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1 or /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to team_url(@team), notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to team_url(@team), notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_members
    new_members = Member.find(params[:member_ids].map(&:presence).compact)
    new_members.each do |member|
      @team.team_members.create_or_find_by(member_id: member.id)  
    end
    redirect_to team_url(@team), notice: "Team was successfully updated."
  end

  def remove_member
    @team_member = @team.team_members.find_by_member_id(params[:member_id])
    @team_member.destroy
    redirect_to team_url(@team), notice: "Team member was successfully removed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, data: {turbo: false}) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>
  <div>
    <%= form.label :team_ids %>
    <%= form.collection_select(:team_ids, Team.all, :id, :name, {}, { multiple: true, class: 'select2' }) %>
  </div>

  <div>
    <%= form.label :project_ids %>
    <%= form.collection_select(:project_ids, Project.all, :id, :name, {}, { multiple: true, class: 'select2' }) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
  <p>
    <strong>First name:</strong>
    <%= member.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= member.last_name %>
  </p>

  <p>
    <strong>City:</strong>
    <%= member.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= member.state %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= member.country %>
  </p>

</div>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Show this member", @member %> |
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Members</h1>

<%= link_to "New member", new_member_path %>

<br>
<br>
<table>
  <thead>
    <tr>
      <td>Full Name</td>
      <td>City</td>
      <td>State</td>
      <td>Country</td>
      <td>Teams</td>
      <td</td>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.full_name, member_path(member) %></td>
        <td><%= member.city %></td>
        <td><%= member.state %></td>
        <td><%= member.country %></td>
        <td>
          <% member.teams.each do |team| %>
            <%= link_to team.name, team_path(team) %>
          <% end %>
        </td>

        <td>
          <% member.projects.each do |project| %>
            <%= link_to project.name, project_path(project) %>
          <% end %>
        </td>
        <td><%= button_to "Delete", member, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @member %>

<div>
  <%= link_to "Edit this member", edit_member_path(@member) %> |
  <%= link_to "Back to members", members_path %>

  <%= button_to "Destroy this member", @member, method: :delete %>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<%= link_to "New project", new_project_path %>

<br>
<br>

<table>
  <thead>
    <tr>
      <td>Name</td>
      <td</td>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= button_to "Delete", project, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

<%= form_with(url: add_members_project_path)  do |form| %>
  <%= form.select(:member_ids, Member.all.collect {|m| [ m.first_name, m.id ] }, 
                  {}, 
                  { :multiple => true, class: 'select2', placeholder: 'Add members'}) %>

  <%= form.submit %>
<% end  %>

<br>
<br>
<h3>Project Members</h3>
<table>
  <thead>
    <tr>
      <td>Name</td>
      <td</td>
    </tr>
  </thead>
  <tbody>
    <% @project.members.each do |member| %>
      <tr>
        <td><%= member.full_name %></td>
        <td><%= link_to 'remove', remove_member_project_path(@project, member), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>